### ISSUE TITLE
v4_format=prefix;resource=DE // v4_format=prefix&resource=DE

### ISSUE THREAD

**Issue by avter** [macskas/geoip-ripe-ipset#1]
./ipset_ripe.pl -c DE
Fri Apr 30 17:40:57 2021 INFO  > process_country_ipset(DE)
Fri Apr 30 17:40:57 2021 ERROR > Unable to retrieve database from https://stat.ripe.net/data/country-resource-list/data.json?v4_format=prefix;resource=DE. Non-200 response

fix is 
my $url_ripe = "https://stat.ripe.net/data/country-resource-list/data.json?v4_format=prefix&resource=";

**Comment by macskas** [comment]
fixed.
