### ISSUE TITLE
[question] not clear what this script does.

### ISSUE THREAD

**Issue by BenceBakos** [macskas/geoip-ripe-ipset#2]
I had days of pain trying to denie every country except HU from one server.

Found this repo just now after problems with geoip module, getting the database etc.

What  
```
perl ipset_ripe.pl -c DE,LU
```
do?
Denies all from DE,LU? 
Or those are the accepted ip-s?

**Comment by BenceBakos** [comment]
This scripts creates an ipset, which we can use in iptables to block OR allow IPs from country we selected. 
Blocking/allowing depends on the iptables rule.
https://wiki.archlinux.org/title/Ipset

@macskas  Correct?

**Comment by macskas** [comment]
yes, thats correct.
